//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareMarketData.Entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPrice
    {
        public int Id { get; set; }
        public string ISIN { get; set; }
        public string SctySrs { get; set; }
        public Nullable<decimal> OpenPrice { get; set; }
        public Nullable<decimal> HighPrice { get; set; }
        public Nullable<decimal> LowPrice { get; set; }
        public Nullable<decimal> ClosePrice { get; set; }
        public Nullable<decimal> LastPrice { get; set; }
        public Nullable<decimal> PrviousClosePrice { get; set; }
        public Nullable<int> TtlTradgVol { get; set; }
        public string TradDt { get; set; }
        public string TtlNbOfTxsExctd { get; set; }
        public int Stock_NameId { get; set; }
    
        public virtual Stock_Names Stock_Names { get; set; }
    }
}
