//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareMarketData.Entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Names
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock_Names()
        {
            this.StockPrices = new HashSet<StockPrice>();
        }
    
        public int ID { get; set; }
        public string SName { get; set; }
        public string ISIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockPrice> StockPrices { get; set; }
    }
}
